export INCLUDE_PGP4_6G = 1

# Define target part
export PRJ_PART = XCU55N-FSVH2892-2L-E

# Use top level makefile
include ../shared_version.mk
include ../shared_pcie_config.mk
include ../../submodules/ruckus/system_vivado.mk
