export GIT_BYPASS  = 1

# Define Firmware Version Number
export PRJ_VERSION = 0x00000001

# Define target output
target: vcs

# Define target part
export PRJ_PART = XC7K325TFFG900-2

# Keep unused source code 
export REMOVE_UNUSED_CODE = 1

# Use top level makefile
include ../../submodules/ruckus/system_vivado.mk
