
# Define target output
target: prom

# Prom type:
# s25fl128sxxxxxx0-spi-x1_x2_x4

# Define Firmware Version Number
export PRJ_VERSION = 0x00000005

# Define target part
export PRJ_PART = XC7K70Tfbg484-2

# Use top level makefile
include ../../submodules/ruckus/system_vivado.mk

