export INCLUDE_PGP3_10G = 1

# Define Firmware Version Number
export PRJ_VERSION = 0x00000008

# Define target part
export PRJ_PART = xcku115-flvb2104-2-e

# Define target output
target: prom

# Use top level makefile
include ../../submodules/ruckus/system_vivado.mk
