
export GIT_BYPASS  = 1

# Define target output
target: prom

# Define Firmware Version Number
export PRJ_VERSION = 0x00000002

# Define target part
export PRJ_PART = XC7K325TFFG900-2

# Define the Microblaze source path
#export SDK_SRC_PATH = $(PROJ_DIR)/../../../common/core/src

# Use top level makefile
include ../../submodules/ruckus/system_vivado.mk

