###################
ClinkTop:
###################
  PllConfig[:]: '85MHz'
  ###################
  Ch[:]:
    LinkMode: Medium
    DataMode: 12Bit
    FrameMode: Frame
    TapCount: 4
    DataEn: True
    Blowoff: False
    BaudRate: 9600 # units of bps
    SerThrottle: 30000 # (30ms x 1us throttle rate) = 10000
    SwControlValue: 0x0
    SwControlEn: 0x0
    HSkip: 0x0
    HActive: 0xFFFF
    VSkip: 0x0
    VActive: 0xFFFF
    ###################
    UartJaiGo5000m: # Jai-GO-5000M-PMCL-UV UART interface
      TM: '1'   # 1: On
      TI: '13'  # 13: CL_CC1_In
      TA: '3'   # 3: LevelLow
      EM: '2'   # 2: TriggerWidth
      TAGM: '3' # 3: Geometry_1X4_1Y
      BA: '2'   # 2: Mono12
      CLCF: '2' # 2: 84.9MHz
###################
TrigCtrl[0]:
  EnableTrig: True
  InvCC: True # Active LOW Pulse
  TrigMap: ChA # ChA = pgpTrigger(0)
  TrigPulseWidth: 100.0 # units of us
  TrigMask: 0x1 # CC1 trigger
#########################################################################################################
