export INCLUDE_PGP4_6G = 1

# Prom type: s25fl128sxxxxxx0-spi-x1_x2_x4
target: prom

# Define target part
export PRJ_PART = XC7K70Tfbg484-2

# Use top level makefile
include ../shared_version.mk
include ../../submodules/ruckus/system_vivado.mk
