export INCLUDE_PGP4_10G = 1

# Define target part
export PRJ_PART = XCKU040-FFVA1156-2-E

# Use top level makefile
include ../shared_version.mk
include ../shared_pcie_config.mk
include ../../submodules/ruckus/system_vivado.mk
