export INCLUDE_PGP3_10G = 0

# Define Firmware Version Number
export PRJ_VERSION = 0x0000000C

# Define target part
export PRJ_PART = xcku115-flvb2104-2-e

# Define target output
target: prom

# Use top level makefile
include ../../submodules/ruckus/system_vivado.mk
