export INCLUDE_PGP4_6G = 0

# Define target part
export PRJ_PART = xcku115-flvb2104-2-e

# Use top level makefile
include ../shared_version.mk
include ../shared_pcie_config.mk
include ../../submodules/ruckus/system_vivado.mk
