export INCLUDE_PGP3_10G = 0

# Define release
export RELEASE = ClinkKcu1500Pgp2b

# Define target part
export PRJ_PART = xcku115-flvb2104-2-e

# Use top level makefile
include ../shared_pcie_config.mk
include ../../submodules/ruckus/system_vivado.mk
